export { default as About } from './about/About' 
export { default as Projects} from './projects/Projects' 
export { default as Skills } from './skills/Skills' 
export { default as Header } from './header/Header'
export { default as Footer } from './footer/Footer'
export { default as Navbar } from './navbar/Navbar'